# Generated by Django 2.2.5 on 2019-09-11 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('columboAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='episode',
            name='season',
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('appears_in', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='columboAPI.Episode')),
                ('played_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='columboAPI.Actor')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='director',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='columboAPI.Director'),
        ),
        migrations.AddField(
            model_name='episode',
            name='writer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='columboAPI.Writer'),
        ),
    ]
