# Generated by Django 2.2.5 on 2019-09-10 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('columboAPI', '0002_auto_20190910_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='columboAPI.Director'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='columboAPI.Writer'),
        ),
    ]
