# Generated by Django 2.2.5 on 2019-09-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columboAPI', '0004_auto_20190911_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='air_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='ep_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='fun_facts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='runtime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
